#! /usr/bin/env python

import os.path
from mcia_irods_utils import IrodsCommand, iargw, isrel, guess_icwd

ils = IrodsCommand( "ils" )

if __name__ == "__main__":
    import sys

    icwd = guess_icwd()
    args = iargw( sys.argv[1:] )

    # because we spawn ils in a subprocess, we need to expand relative paths here,
    # otherwise, ils wouldn't recognize wd correctly
    newargs = []
    for arg in args:
        if isrel( arg ) and not arg.startswith( '-' ):
            arg = os.path.normpath( icwd + '/' + arg )
        newargs.append( arg )

    newargs = newargs or [icwd]

    retcode, output = ils(newargs)

    print output.rstrip()

    sys.exit( retcode )
